### PR TITLE
Plot sol dev

### PR DESCRIPTION
**Pull request by sshiraiwa**
This pull modify plot panel so that it allows for 
* reading data from an arbitrary local directory.
* recording the remote directories in pull-down menu
It also
* avoid hang-up when ssh connection was not properly setup
* error message shows more useful information

### CODE REVIEW

**Comment by mortezah** [comment]
@sshiraiwa 

Thanks. This seems to work as expected.

I would like to make an improvement to this for the adaptive workflow. This is what I have in mind:

It would be nice if I can add a suffix to each solution and mesh. This suffix would let me know which adapt-solve the solution and mesh files correspond to. For example I would have something like 

solr_E_adapt_iter_0.000000 ---> the solution after the 1st solve-adapt 
solr_E_adapt_iter_1.000000 ---> the solution after the 2nd solve-adapt
solr_E_adapt_iter_2.000000 ---> the solution after the 3rd solve-adapt

I have already done this for the mesh and solution files. The problem with that is that the plot would not see these files because they have different names now. Do you think it would be better to have multiple solution folders and suffix them with the adapt # but use the default naming convention of petram for the mesh and solution files? That way I can just point the desired folder (e.g. sol_adapt_iter_0) to the plot option in petram. If I do this what are the files that have to go to that folder? Do I need anything besides the mesh and solution files?

**Comment by sshiraiwa** [comment]
Thank you for the review. Let me merge this.
I think it makes more sense to store the intermediate solutions under sub-folders.
Time domain solver saves checkpoint solutions in sub-folder and saves the final solution in the
top level.
The plot solution panel already checks subfolders. But the name should start with "case". So, can you
save solutions under "case_xxx"? This part is not checked. So if you find something, please open
an issue.

**Comment by mortezah** [comment]
@sshiraiwa 
can you point me to and example in the code where the solutions are written into sub-folders?

**Comment by sshiraiwa** [comment]
How about this method?
https://github.com/piScope/PetraM_Base/blob/next/petram/solver/parametric.py#L111

**Comment by mortezah** [comment]
@sshiraiwa 

I did manage to save the solutions in separate folders, and the plot solution panel seems to recognize the sub-folders properly, and I can visualize the solution after each adapt.

An unrelated questions: Is it possible to see the actual mesh (not just the fields) in the plots?

**Comment by sshiraiwa** [comment]
Glad to hear it. One thing we can do is to plot a constant, say 1, on the boundary plot. 
Use refinement 1 and average. Then, change the property of plot to see the triangle edges.
If you are asking the slice of mesh, we don't have that feature yet. Happy to see your contribution ;D

**Pull request merged**
